### ISSUE TITLE
The message about the experience gained does not fit on the screen.

### ISSUE THREAD

**Issue by buinsky** [Zero-to-Heroes/firestone#110]
The message about the experience gained after the match does not fit on the screen.

![image](https://user-images.githubusercontent.com/9297293/184103077-d0382938-7961-499a-aeae-ae42d51618a4.png)

**Comment by sebastientromp** [comment]
Thanks for the report! There are a few known issues when the Windows zoom level is not 100%, or when you're using multiple displays with different screen resolutions. Are you in one of these situations?

**Comment by buinsky** [comment]
> Are you in one of these situations?

My Windows zoom is 125%.

**Comment by sebastientromp** [comment]
Thanks, there are indeed sometimes issues with non-100% DPI (especially if you have multiple monitors with different DPIs). I have an item on my list for the next iteration to look into this, so I should get to it pretty soon.

**Comment by sebastientromp** [comment]
This should be fixed now. Let me know if it should be reopened :)
