### ISSUE TITLE
Idea: Combine counters into a single block

### ISSUE THREAD

**Issue by piedpiper358** [Zero-to-Heroes/firestone#176]
**More and more different counters appear in Firestone. And when several of them display at the same time, it doesn't look very nice.**

![2022-08-25_03-57-48 2](https://user-images.githubusercontent.com/43519401/187513485-09e6b1e9-c300-42e7-bd11-812f355a9c3f.png)

**So I came up with a suggestion: combine all counters (except for the attack counter) into a single block of counters, so that it looks something like banned tribes widget in Battlegrounds.**

![2022-08-29_01-13-10](https://user-images.githubusercontent.com/43519401/187513836-0248a02b-6d56-43bd-b3db-db2122cf6f55.png)

**Comment by sebastientromp** [comment]
I would wait until people really express the need for it. I've seen people (myself included) place counters all over the place, depending on what they are for. If they were grouped together, it would prevent them from doing it.
So maybe it will be needed in the future, but right now I think grouping counters together can do as much harm as good.

**Comment by piedpiper358** [comment]
Maybe we can add such option in settings?

**Comment by sebastientromp** [comment]
It could definitely be a possibility, however the amount of work needed vs the expected value is pretty high.
