### ISSUE TITLE
fraps breaks firestone

### ISSUE THREAD

**Issue by g-k-m** [Zero-to-Heroes/firestone#182]
whenever i start fraps to see my fps, it breaks firestone overlay. then i have to restart game to fix it, but then i have to start fraps again because hs sometimes resets my custom fps settings (i have 240 fps in the settings file) to its default, and i need fraps to check what fps i have. fps in hs actually makes animations go faster and provides a real advantage, so it is a must. could you make firestone not break when using fraps?

**Comment by sebastientromp** [comment]
Could you reproduce the issue (make firestone crash) then send me the logs at seb@firestoneapp.com?

You can get the logs like this: https://support.overwolf.com/en/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs

**Comment by g-k-m** [comment]
it doesn't crash, just firestone overlay stops showing after i launch fraps

**Comment by sebastientromp** [comment]
Closing the issue, as right now I don't think there is anything I can do on my side without more logs.
