### ISSUE TITLE
[Bug] Awarded Top 4 finish achievement after finishing 5th

### ISSUE THREAD

**Issue by roberts-g** [Zero-to-Heroes/firestone#19]
I was awarded the "Finished top 4 with King Mukla" despite finishing 5th. Before the final fight, I was in 4th place, so I guess the achievement might be being awarded based on leaderboard position before the final fight.

**Comment by sebastientromp** [comment]
Thanks for the report! It's possible indeed that I detect the "match end" event before the final position is detected, I'll look into that.

Thanks again!

**Comment by sebastientromp** [comment]
PS: could you attach the Power.log file? It is in your HS install folder / Logs (it should be pretty big)

**Comment by roberts-g** [comment]
Just saw this comment, and it looks like the logs from that game have already been overwritten. Sorry :(

**Comment by sebastientromp** [comment]
No worries, I found out what the issue was. The final change in leaderboard positions is logged after the event I usually use to decide when the game is over.
It will be fixed in the next release, which will ship either tomorrow (Monday) or Tuesday

**Comment by sebastientromp** [comment]
Fixed :)
