### ISSUE TITLE
[Bug] Achievements not awarded when playing as Millificent Manastorm

### ISSUE THREAD

**Issue by roberts-g** [Zero-to-Heroes/firestone#20]
Just won a game as Millificent Manastorm but did not receive the achievements for playing/top 4/winning with her. Also saw that I didn't get any of the achievements for playing minions/getting triples.
At the end of the game, I did get some of the 'Tracking' achievements (Assassin, Face is the Place, Shopping!)

[Link to power.log](https://drive.google.com/file/d/1TtWaSKtYh3jRq6BW7yKUN_SXu5GRV7vO/view?usp=sharing) (couldn't upload to GitHub as it was too big) - the game is between 13:30 and 14:15

**Comment by roberts-g** [comment]
After another two games with Millificent, the achievements unlocked for her, although I did restart Hearthstone in between

**Comment by sebastientromp** [comment]
Thanks! So this means it's probably an issue with the notification system. There might have been an error that prevented the notif from showing.
Next time this happens, could you send me a bug report using the "report a bug" button from the Firestone window? It will automatically upload all the log files so I can have a look at whether an error occurred.

Thanks again for the reports!
