### ISSUE TITLE
Update completed tasks

### ISSUE THREAD

**Issue by menthil** [Zero-to-Heroes/firestone#205]
Hello.

Now that I completed all tasks of all the mercenaries I have some mercenaries which tasks were not tracked, some because I didn't use it in the time when I completed and Baine that I forgot to open Firestone when I completed task 18 and I got an awfull 17/18.

Can you develop any feature to update those numbers?

Thank you and congrats for your awesome app

![firestone](https://user-images.githubusercontent.com/4276500/188976814-9055b500-0411-42aa-a24a-da2cb511db90.png)

**Comment by piedpiper358** [comment]
By the way, it seems useful to me to loop the list of mercenary tasks: that is, when you on the first task and go to the previous task, you get to the 18th one. It will avoid a lot of unnecessary clicks when manually installing fully upgraded mercenaries.

**Comment by piedpiper358** [comment]
You can set them manually with Ctrl + click (see toltip in column header), but it's certainly not very convenient to do this for all mercenaries for all 18 tasks.

By the way, it seems useful to me to loop the list of mercenary tasks: that is, when you on the first task and go to the previous task, you get to the 18th one. It will avoid a lot of unnecessary clicks when manually installing fully upgraded mercenaries.

**Comment by menthil** [comment]
Almost one year using this app, wanting this feature and it was implemented!!! I didn't realize the tooltip. Thank you!!

**Comment by piedpiper358** [comment]
I was happy to help you)
