### ISSUE TITLE
Duels heroes search doesn't work

### ISSUE THREAD

**Issue by piedpiper358** [Zero-to-Heroes/firestone#207]
![2022-09-10_00-34-02](https://user-images.githubusercontent.com/43519401/189449443-9d1e5f94-faa9-4f2c-a4d3-70f25320c667.png)

**Comment by piedpiper358** [comment]
@sebastientromp 

Performing a hero search while duels-time-filter is set to 'Past 100 days' breaks the search and results no longer change when changing filters or search string until you reload the application.

**Steps to reproduce the bug:**

0. The duels-time-filter is set to anything other than 'Past 100 days'
1. Enter a query in the search bar, for example, Reno.
2. Change duels-stat-type-filter value - make sure everything works fine and treasures with 'Reno' in name are given out.
3. Change the duels-time-filter value to 'Past 100 days'.
4. Change the duels-stat-type-filter value - make sure everything is broken and the search results won't change no matter what you do until you restart the application.

![2022-10-14_20-18-17](https://user-images.githubusercontent.com/43519401/195908309-40cb90d8-3dc2-4628-a153-33abec7db403.png)

**Comment by sebastientromp** [comment]
I couldn't reproduce the issue - I follow the exact steps you mentioned and was still able to update all the filters.
Maybe it's something I did in a recent commit that fixed it? Would you mind testing it again after pulling from master?

**Comment by piedpiper358** [comment]
Yes, indeed the issue is no longer reproduced. Perhaps if now not only heroes can be found using search bar, maybe we should change placeholder to "Search card..." instead of "Search hero..."? We also should definitely add an empty state here.
