### ISSUE TITLE
Galakrond achievement ideas

### ISSUE THREAD

**Issue by sebastientromp** [Zero-to-Heroes/firestone#21]
* [ ] Deal more than 40 / 60 / 80 / 100 / 150 damage in a single turn as Khadgar
* [ ] Freeze minions against Avalanchan?

**Comment by mSterian** [comment]
I'm not personally interested in this adventure as I've specified before but one idea that struck me is to beat each encounter with every class. Meaning, track each class for each boss, and maybe also a meta achievement for having beat all bosses each with every hero.

**Comment by sebastientromp** [comment]
> I'm not personally interested in this adventure as I've specified before but one idea that struck me is to beat each encounter with every class. Meaning, track each class for each boss, and maybe also a meta achievement for having beat all bosses each with every hero.

That's valid only for Heroic, right?

**Comment by mSterian** [comment]
> > I'm not personally interested in this adventure as I've specified before but one idea that struck me is to beat each encounter with every class. Meaning, track each class for each boss, and maybe also a meta achievement for having beat all bosses each with every hero.
> 
> That's valid only for Heroic, right?

Yes.

**Comment by sebastientromp** [comment]
Let's go for it

**Comment by sebastientromp** [comment]
https://www.reddit.com/r/hearthstone/comments/ese8ml/fun_ways_to_defeat_avalanchan_inspired_by_reddit/

**Comment by sebastientromp** [comment]
Closing for now, as achievements are not under active development at the moment. This might change if I can find a nice hook to give more value to Firestone's achievements.
