### ISSUE TITLE
Info is leaked when opponent uses Sphere of Sapience

### ISSUE THREAD

**Issue by piedpiper358** [Zero-to-Heroes/firestone#211]
![2022-09-11_23-51-06](https://user-images.githubusercontent.com/43519401/189554339-051d5e2f-196f-425c-a442-10781dfefabc.png)
![2022-09-11_23-52-08](https://user-images.githubusercontent.com/43519401/189554278-135b68e3-850b-431d-b92b-2be60bb93fd5.png)

**Comment by sebastientromp** [comment]
Should be fixed now
