### ISSUE TITLE
Mercenaries-out-of-combat-player-team displays incorrect equipment level

### ISSUE THREAD

**Issue by piedpiper358** [Zero-to-Heroes/firestone#212]
Mercenaries-player-team:

![2022-09-13_16-06-49](https://user-images.githubusercontent.com/43519401/189915197-6c1c3ec0-6a0d-4fba-929d-c29759594c57.png)

Mercenaries-out-of-combat-player-team:

![2022-09-13_16-05-16](https://user-images.githubusercontent.com/43519401/189915188-8238cb63-d59b-464c-a30e-8678c43983fd.png)

**Other equipment**

Mercenaries-player-team:

![2022-09-13_15-51-50](https://user-images.githubusercontent.com/43519401/189914939-2cab40d7-0076-4be6-b0ec-c0c7a787883a.png)

Mercenaries-out-of-combat-player-team:

![2022-09-13_15-50-37](https://user-images.githubusercontent.com/43519401/189914928-51dc7633-2377-4387-8346-e47da35377de.png)

**Comment by sebastientromp** [comment]
This is fixed with one of your recent PRs, correct?

**Comment by piedpiper358** [comment]
Yeah
