### ISSUE TITLE
Twich Extension

### ISSUE THREAD

**Issue by egorzainullin** [Zero-to-Heroes/firestone#23]
Hello, I am not sure that issue about twich extension should be written here.

First of all, I want to report a bug that image of hero power of classic heroes is not shown correctly.
![image](https://user-images.githubusercontent.com/22919120/82729401-f1782d80-9cff-11ea-8d5f-242f483c48a2.png)
Also link to licence in extension info is not correct, because Github says that this page does not exist 
![2](https://user-images.githubusercontent.com/22919120/82729442-503da700-9d00-11ea-9df9-4effc90a3ffb.png)
Also I have a suggestion of enhancement. It would be great if you add hide button to hide deck like HS decktracker does.

**Comment by sebastientromp** [comment]
Hey, thanks for the report! 

> First of all, I want to report a bug that image of hero power of classic heroes is not shown correctly.

Got it, I'll have a look

>  Also link to licence in extension info is not correct, because Github says that this page does not exist

Indeed, the path changed and I forgot to update it on Twitch

>  Also I have a suggestion of enhancement. It would be great if you add hide button to hide deck like HS decktracker does.

Will do! You used to be able to toggle it off simply by clicking on the Twitch icon, but it seems that the behavior changed. I will roll out a new version this week that restores the "hide" button.

Thanks for the feedback!

**Comment by sebastientromp** [comment]
I've submitted a new version to Twitch that should fix that, as well as providing a workaround to the "copy deckstring" issue on Chrome. I'll update this issue when the extension is live

**Comment by sebastientromp** [comment]
New release is live, let me know if anything is still amiss.

Thanks again for the report!
