### ISSUE TITLE
Genarate card images

### ISSUE THREAD

**Issue by piedpiper358** [Zero-to-Heroes/firestone#266]
It's necessary to generate images for the following cards:
* All versions of Nzoth merc ([1](https://static.firestoneapp.com/cards/enUS/512/LT23_025H_01.png), [2](https://static.firestoneapp.com/cards/enUS/512/LT23_025H_02.png), [3](https://static.firestoneapp.com/cards/enUS/512/LT23_025H_03.png)) and his [Corrupted Viscera](https://static.zerotoheroes.com/cards/enUS/512/LT23_025P3_05.jpg) ability and equipment
* [Dark Depths Feastbringer](https://static.firestoneapp.com/cards/enUS/512/LT23T_105_01.png), [Clownfish](https://static.firestoneapp.com/cards/enUS/512/LT23T_104_01.png), [Bilefin Tidehunter](https://static.firestoneapp.com/cards/enUS/512/LT23T_102_01.png),  [Sunken Scavenger](https://static.firestoneapp.com/cards/enUS/512/LT23T_113_01.png), Murloc On A Break ([1](https://static.firestoneapp.com/cards/enUS/512/LT23T_101_01.png),  [2](https://static.firestoneapp.com/cards/enUS/512/LT23T_101_02.png), [3](https://static.firestoneapp.com/cards/enUS/512/LT23T_101_03.png)), Voidgill ([1](https://static.firestoneapp.com/cards/enUS/512/LT23T_103_01.png), [2](https://static.firestoneapp.com/cards/enUS/512/LT23T_103_02.png)), Twin-fin Fin Twin ([1](https://static.firestoneapp.com/cards/enUS/512/LT23T_100_01.png),  [2](https://static.firestoneapp.com/cards/enUS/512/LT23T_100_02.png))
* ['Spectral Kitty 1'](https://static.firestoneapp.com/cards/enUS/512/LETL_1138_01.png)  mercs treasure
* All tiers of [Sprouting Tentacles](https://static.firestoneapp.com/cards/enUS/512/LT23_025T1_01.png) mercs treasure

* [King of Naga](https://static.firestoneapp.com/cards/enUS/512/TB_BaconShop_HP_041j.png)  BG hero power

* New card backs ([1](https://static.firestoneapp.com/cardbacks/512/349.png), [2](https://static.firestoneapp.com/cardbacks/512/352.png), [3](https://static.firestoneapp.com/cardbacks/512/353.png))

![2022-10-17_02-33-05](https://user-images.githubusercontent.com/43519401/196410968-5e01a9b1-c37f-4c7c-9ce5-611b438b292c.png)
![2022-10-18_14-26-21](https://user-images.githubusercontent.com/43519401/196417176-7c60c0ec-611c-42ce-8bbf-6929beda5f96.png)

**Comment by sebastientromp** [comment]
Should be ok now.
Just be sure to use the `firestoneapp` domain for cards, e.g. https://static.firestoneapp.com/cards/enUS/512/LT23_025P3_05.png

**Comment by piedpiper358** [comment]
There's still a problem with Nzoth's equipment

**Comment by piedpiper358** [comment]
All equipment in all tiers

https://static.firestoneapp.com/cards/enUS/512/LT23_025E1_04.png
https://static.firestoneapp.com/cards/enUS/512/LT23_025E2_04.png
https://static.zerotoheroes.com/cards/enUS/512/LT23_025E3_04.jpg
