### ISSUE TITLE
Phantom BG hero

### ISSUE THREAD

**Issue by piedpiper358** [Zero-to-Heroes/firestone#269]
**It's necessary to solve the problem of the phantom BG hero. This is hero with id [TB_BaconShop_HERO_102](https://static.zerotoheroes.com/hearthstone/cardart/256x/TB_BaconShop_HERO_102.jpg) - Murloc Lord Saurfang**

![2022-10-23_23-48-32](https://user-images.githubusercontent.com/43519401/197417533-b92c123e-3881-4a90-b80d-c16387163963.png)

![2022-10-23_23-41-38](https://user-images.githubusercontent.com/43519401/197417462-52c83ff1-024b-4596-9a3b-22c3591110f0.png)

**Comment by ytpbit2** [comment]
This is the new hero coming, img usually take but time

**Comment by sebastientromp** [comment]
It's an issue where the hero skin is not properly considered as a skin. I don't know why though, as I just checked the code and everything looks correct.

I will add a double check when building the stats

**Comment by sebastientromp** [comment]
Found the issue, it should be fixed with the next stats refresh tomorrow
