### ISSUE TITLE
Genarate card images 

### ISSUE THREAD

**Issue by piedpiper358** [Zero-to-Heroes/firestone#281]
@sebastientromp, It's necessary to generate images for the following cards:

*  All N'zoth equipment of all tiers

https://static.firestoneapp.com/cards/enUS/512/LT23_025E1_04.png
https://static.firestoneapp.com/cards/enUS/512/LT23_025E2_04.png
https://static.zerotoheroes.com/cards/enUS/512/LT23_025E3_04.jpg

*  Seeing Red treasure of all tiers https://static.firestoneapp.com/cards/enUS/512/LETL_1147_01.png

![2022-10-25_01-07-33](https://user-images.githubusercontent.com/43519401/197639230-3fee8dc1-ba0a-450d-88a5-d1b506f4affb.png)

**Comment by sebastientromp** [comment]
These images have been regenerated

**Comment by piedpiper358** [comment]
Nice work!
