### ISSUE TITLE
Hide loading window in dev mode

### ISSUE THREAD

**Issue by piedpiper358** [Zero-to-Heroes/firestone#287]
Could you please hide this window when starting Firestone in developer mode? When you restart the application dozens of times a day, it is very annoying.

![2022-11-02_15-59-52](https://user-images.githubusercontent.com/43519401/200195631-44a797ac-a7ab-4309-bcae-e640a19f2393.png)

**Comment by sebastientromp** [comment]
Will do :)

**Comment by piedpiper358** [comment]
Nice!

**Comment by piedpiper358** [comment]
@sebastientromp, Now Alt + C doesn't work while in game((

**Comment by sebastientromp** [comment]
Yes I messed up something. It's fixed on `master`.
