### ISSUE TITLE
Issues on PvP Teams tab

### ISSUE THREAD

**Issue by piedpiper358** [Zero-to-Heroes/firestone#297]
Again there are issues with some teams on PvP Teams tab

![2022-11-09_16-29-07](https://user-images.githubusercontent.com/43519401/200843178-4f62c6ca-52a6-4f78-8573-55c187a87bc7.png)

**Comment by sebastientromp** [comment]
Thanks. In the next version I'll deactivate the mercs PvP tabs, because there isn't enough data to make them meaningful, and they are barely used.

I will probably revisit them at some point in the future, maybe in a different form

**Comment by piedpiper358** [comment]
It's a pity. I would like this information to remain in app.
I think this is more of a problem with the unpopularity of Mercenaries mode itself, and especially PvP, than a problem of Firestone. When I was playing PvP, meta presented on the tab looked up to date.

**Comment by sebastientromp** [comment]
Yes, I understand. But today there are ~30 people accessing the tab daily, and the sample size of the data is way too small.
Maybe doing something like I do today for Duels that showcases teams that got >W% winrate over the course of a few games?
