### ISSUE TITLE
README contirbution info 

### ISSUE THREAD

**Issue by sunnamed434** [Zero-to-Heroes/firestone#312]
What do you think about moving the [text](https://github.com/Zero-to-Heroes/firestone#contributing) about contributing into CONTRIBUTING.md ?

**Comment by sebastientromp** [comment]
Yes good point, I'll do it

**Comment by sunnamed434** [comment]
If you don't mind I could contribute by myself =)

**Comment by sebastientromp** [comment]
I will do it, as the content of the section needs to be updated as well :)

**Comment by sunnamed434** [comment]
Ok np

**Comment by sebastientromp** [comment]
Done. If you want to improve it though (content and/or formatting), feel free :)

**Comment by sunnamed434** [comment]
Where could I do the changes? Right in the master branch?

**Comment by sebastientromp** [comment]
If it's just that file, you can edit it on GitHub, then it should offer you to open a pull request to propose your changes for merge into the master branch

**Comment by sunnamed434** [comment]
I made two pull requests, idk why I'm unable to do it one pull -_0

**Comment by sebastientromp** [comment]
Thanks!

If you want to do everything in a single PR, I think you need to follow the "usual" flow: make a fork, clone it, create a branch on your fork, do your changes locally, push it to your remote, and open a PR to merge your branch into the master here.

**Comment by sunnamed434** [comment]
Oh, yeah, thanks for the information!
