### ISSUE TITLE
Battle luck

### ISSUE THREAD

**Issue by edobrb** [Zero-to-Heroes/firestone#315]
Is there a way to calculate the average battle luck for all logged games? It should be an interesting parameter and should tend to 0 with a large number of played games.

**Comment by sebastientromp** [comment]
Hey! There isn't at the moment, and I'm not sure I want to do more stats on battle luck. The main reason is that the simulator is not perfect, and never will.
Having it mess up for a game or two isn't a big deal, but if we start having stats to take the history of all the battles, these inaccuracies will become much more visible and annoying.
