### ISSUE TITLE
Update scaling of graphs

### ISSUE THREAD

**Issue by GCorbel** [Zero-to-Heroes/firestone#321]
In last 7 days, I went from 7k1 to 7k8. Here is the corresponding graph : 

![image](https://user-images.githubusercontent.com/1296201/221366619-91f5f74a-f3b2-4dc3-b7ba-9c798c6979e3.png)

My lowest rank was 6k9. In order to have more meaningful representation, I think the Y-value should be around 6k8.

When filters are changed, the graph should be scaled according to min and max rank.

**Comment by sebastientromp** [comment]
Yeah that makes sense, I'll update it. Thanks for the suggestion!

**Comment by GCorbel** [comment]
it's done. Thanks.
