### ISSUE TITLE
Collection.json no longer updating

### ISSUE THREAD

**Issue by HugoKornelis** [Zero-to-Heroes/firestone#331]
Since October 29, the file "collection.json" in the directory %appdata%\Overwolf\(random string of letters) no longer updates when I use Firestone.
I use this file as input for my "missing dust" tracker (a silly thing I built for myself to track how much dust I need in order to have a full collection, a full golden collection, etc etc). Are you now saving this data elsewhere? If so, could you kindly tell me where, so I can try to adapt my import process?
Thanks in advance!

**Comment by sebastientromp** [comment]
Let me check, that's not intended.
I did modify a lot of things internally to reduce the amount of processing done needlessly, and I might have been too strict with this piece

**Comment by sebastientromp** [comment]
@HugoKornelis Could you try to simply go to the Collection tab in the app? I think this should be enough to trigger the update

**Comment by HugoKornelis** [comment]
Hey, thanks @sebastientromp - that did the trick!
