### ISSUE TITLE
Keep % in mulligan overview is wrong

### ISSUE THREAD

**Issue by borisbabic** [Zero-to-Heroes/firestone#342]
The % in the overlay is different than the percentage in the app.

https://github.com/Zero-to-Heroes/firestone/blob/master/libs/constructed/common/src/lib/services/constructed-mulligan-guide.service.ts#L342

It should be the % of times people decide to keep it when it's offered, like I assume it is in the card stats in the app, not the % of times the reason it's in your hand after the mulligan because you kept it.

**Comment by sebastientromp** [comment]
You're totally right. This was correctly computed in other parts of the app (eg https://github.com/Zero-to-Heroes/firestone/blob/0247e1b9ea7fcd2a5f9424e8b356f418c9e83fde/libs/legacy/feature-shell/src/lib/js/components/decktracker/main/constructed-meta-deck-details-card-stats.component.ts#L252) but was done incorrectly here, and in the mirror Arena class.

Thanks for finding this!
