### ISSUE TITLE
Firestone is not launching

### ISSUE THREAD

**Issue by Gonz1g** [Zero-to-Heroes/firestone#347]
Firestone is not launching

**Comment by sebastientromp** [comment]
Hello, thanks for reaching out!
Could you have a look at the troubleshooting steps from https://github.com/Zero-to-Heroes/firestone/wiki/FAQ---Troubleshooting and let me know if anything helps?

**Comment by Gonz1g** [comment]
> Hello, thanks for reaching out! Could you have a look at the troubleshooting steps from https://github.com/Zero-to-Heroes/firestone/wiki/FAQ---Troubleshooting and let me know if anything helps?

Its just not launching.It doesn't even show up in Task Manager. Reinstalling it didn't help.

**Comment by Gonz1g** [comment]
Fixed it by adding it to the blacklist in goodbye dpi https://static.firestoneapp.com/ n https://static.firestoneapp.com/

**Comment by sebastientromp** [comment]
Thanks for the update! Adding this to the troubleshooting guide above
