### ISSUE TITLE
Tier list ad after opening a pack would be nice

### ISSUE THREAD

**Issue by EquohluxX** [Zero-to-Heroes/firestone#4]
Directly beloy the opened cards.
The same way HearthArena does this in their overlay.
www.heartharena.com

**Comment by sebastientromp** [comment]
For now I don't have plans to have a tier list of cards, as this is pretty tough to implement in a meaningful way.
I'll keep that in mind somewhere though, in case the opportunity arises.

Thanks for the suggestion!
