### ISSUE TITLE
[Battleground] Error on Macaw + Golden Goldrinn + Golden Rivendare computation

### ISSUE THREAD

**Issue by avandal** [Zero-to-Heroes/firestone#40]
Looks like Golden Goldrinn is +10/+8 instead of +10/+10 (Maybe check normal Goldrinn too)
![image](https://user-images.githubusercontent.com/12011030/115897497-c68ce100-a45c-11eb-8d09-220b2ed49c4c.png)
![image](https://user-images.githubusercontent.com/12011030/115897597-e0c6bf00-a45c-11eb-82ca-27779446d68e.png)

**Comment by sebastientromp** [comment]
Good catch, it's indeed a bug. It will be fixed in the next release
