### ISSUE TITLE
Add Firestone leaderboards for Battlegrounds

### ISSUE THREAD

**Issue by andrewgiese** [Zero-to-Heroes/firestone#52]
Similar to the leaderboards that were added for Duels, I would love to see leaderboards for Battlegrounds for all of the players that use Firestone. The official leaderboards are nice but one of the big issues with them is you have no idea where you stand if you're outside of the top 200.

Nice to have bonus features:
- See what percentile your current MMR falls into.
- Remove players from the pool if they haven't posted a game for some time period (to discourage camping).

**Comment by sebastientromp** [comment]
The official leaderboards now include more or less everyone, so I will close the issue here. I might still add it in the future (it's on my list), but there is no need to track it here anymore.
