### ISSUE TITLE
Battle simulator is often wrong

### ISSUE THREAD

**Issue by g-k-m** [Zero-to-Heroes/firestone#53]
![8364094 390000001_image](https://user-images.githubusercontent.com/37273303/132094821-5c8931c7-01f3-4d6c-bb20-d44bea1a1457.png)

I have local simulator enabled with the max 15K simulations and yet firestone shows 100.0% loss but I won that fight as u can see, here's another pic from firestone with the team comps before the fight:

![bug](https://user-images.githubusercontent.com/37273303/132098651-e500b095-f53e-4003-99a5-a503fa7de21e.png)

This is 100% firestone's fault, cuz there aren't that many variations of that fight, there are no deathrattles or weird stuff, it should be pretty straightforward for it to calculate with 15K combinations yet it calculates very wrong. Also i had another fight that I had 99.9% chance to win and 0.1% chance to tie, and I tied. I really doubt it was only 0.1%, based on the enemy team comp. Firestone is calculating wrong fix pls

**Comment by sebastientromp** [comment]
Thanks, I'll look into it. The board indeed looks pretty straightforward, apart maybe for the avenge stuff.

**Comment by sebastientromp** [comment]
I found where the issue is. The simulator applies all similar buffs at the same time, instead of one by one. In the past that didn't matter, but because of Whelp Smuggler, it is important now.
This means that the taunt dragon didn't get enough health from the Arm of Empire + Whelp Smuggler buffs.

I will fix it for the release next week :)

**Comment by g-k-m** [comment]
Ye also the way it works now, is when the 6/4 gets attacked, it gains attack from the arm, then the attack is applied, and then if it goes to like -2 hp it gains +3 from the smuggler and it's back to 1 hp

**Comment by sebastientromp** [comment]
Indeed, I saw that as well. There should be no difference whether the attack or the bug is applied first though, add in both cases it ends up at 1hp. Or am I missing something?

**Comment by sebastientromp** [comment]
Once fixed, the win% of the battle you screenshot was actually 100% :)
