### ISSUE TITLE
Tasks from Campire visible during a match

### ISSUE THREAD

**Issue by silviuum** [Zero-to-Heroes/firestone#55]
Hello! This request is regarding the Mercenaries mode.
Do you think it's possible for tasks from Task Board do be visible during a match? I keep forgetting what mercenaries "visit" my village and what their tasks are. I guess it could be implemented next to the "Roles chart" dropdown which is also really valuable. I think it would be a great feature. Thank you for your continuous support of the app!

**Comment by sebastientromp** [comment]
It's actually in, closing the issue :)
