### ISSUE TITLE
Replays vs Thief Rogue are not saved properly

### ISSUE THREAD

**Issue by g-k-m** [Zero-to-Heroes/firestone#58]
Now yesterday i did not encounter that many thief rogues however since I am in top 1K legend the other day i played 5/6 games vs rogue, 1 of them was poison 4 were thief rogue. After that i played 2 thief rogues out of 3 games. Idk if u play but thief rogue changes the avatar and then when u play a rogue class card it changes back due to Maestra which is used to proc double agent and reduce gnoll's cost to 0 (you can play gnoll turn 1 if you draw Secret Passage or turn 2 normally if you draw the gnoll itself or any combination of prep swindle etc.) And in the replays the masked class is saved, so then i look at my history and i see all these different classes that were all thief rogue and it really ruins the entire replay library it's almost unusable i have to check every single one one by one pls fix thx

**Comment by sebastientromp** [comment]
Which version are you on?

**Comment by g-k-m** [comment]
Oh never mind i see it just got fixed with patch 8.4.9, epic fail lmao

**Comment by sebastientromp** [comment]
Haha no worries :)
