### ISSUE TITLE
Add dredge indicator

### ISSUE THREAD

**Issue by g-k-m** [Zero-to-Heroes/firestone#79]
So, the way the Dredge mechanic works is, u take the bottom-est 3 cards of ur deck, pick one, and put that one at the top of ur deck or in some cases draw it immediately. then u put the other 2 cards back in the same order u saw em.

What does this mean? If in the Dredge window u see cards X Y Z, and u pick Y, now the bottomest cards of ur deck will be X Z A, where A is the 4th most bottom card that was in the deck before u dredged.
If u pick X, it will be Y Z A
if u pick Z, it will be X Y A.

What i'm trying to say is, whenever u Dredge, the 2 cards of the 3 that u did not pick, are always the 2 bottom-est cards in ur deck after u have Dredged, and they are in the same order u saw em, and that's extremely important information, i have to write it down every single game somewhere so i don't forget.

There should be an indicator that u can mouse over to show u the bottom-est 2 cards of ur deck after u Dredge, in the order u saw em (leftmost is bottomest, rightmost is top-est, or for the indicator - left card bottommost, right card 2nd bottommost)

This is extremely extremely important and i have to write it down every game or else my winrate will go down 10%+ as a ramp druid player, as it's such crucial information

So, just in case it is still confusing, here's how it works:
1) You dredge, you pick a card
2) The other 2 cards are now the two bottommost cards in your deck, in the order you saw em.
The leftmost card you saw was the bottommost, the middle card was the 2nd bottommost, and the right card was the 3rd bottommost, but you took one of em, so only 2 of those remain (whose identity you know)
3) Regardless of which card you picked, the other 2 are now the first and second bottommost cards in your deck, with the one closer to the left when you saw it being the bottommost, and the other one being the second bottommost
4) When you mouse over the proposed indicator, the left card shown (from the indicator) will be the bottommost, and the right card shown (from the indicator) will be the second bottommost, aka the 2 cards you did not pick from your dredge choice window

Alternatively, you can make it so that in the deck list, the 2 cards you did not pick and are now on the bottom, show a dredge icon. I have my cards sorted by mana so it's not a viable solution to sort the cards based on which ones are on the bottom, so an anchor/dredge icon would be better suited, with the bottomest card having a bigger icon and the 2nd bottomest card having a normal-sized icon. This will make it easier to see the cards without having to explicitly mouse over.

Or, why not both an indicator and a dredge icon in the decklist?

**Comment by sebastientromp** [comment]
Thanks for the suggestion! I'll implement something as soon as I get back from vacation :)

**Comment by g-k-m** [comment]
Just wanna say thanks for implementing this, this saves me actually so much effort!

**Comment by g-k-m** [comment]
Altho, i see u fixed the hooktusk thing where u could see the cards u stole. Obviously that's a huge gameplay advantage, but why do u have to fix it? It's up to hs server to not give away this information to u, u're basically doing the hs team's work for free... It's like u're teaching em that it's fine to let them handle the work to u and be lazy and not hide the information that they're supposed to hide. I bet if i knew how to code this i could make it myself to show the cards. Anyway rant over

**Comment by sebastientromp** [comment]
I totally understand the sentiment :)

The philosophy behind the tracker was to facilitate handling things you already know, i.e. things that are shown in the UI today. It would be possible to get A LOT more information from what is in the logs, but I've chosen not to do it (as an example, beside Hooktusk, every time a card is shuffled back into the opponent's deck - like tradable - I would be able to tell you when it got back to their hand, and things like this).
