### ISSUE TITLE
Feature to add: how many packs or how much dust/money I need at best/ in average to acomplish full collection/one particular expansion in non-golden/golden. (With/without count of current ammount of gold/dust/packs).

### ISSUE THREAD

**Issue by Pycz** [Zero-to-Heroes/firestone#8]

**Comment by sebastientromp** [comment]
Yes, good point. I'm adding it to the backlog

**Comment by sebastientromp** [comment]
I've added the dust count to the app, thanks again for the suggestion :)

I'll add the money / packs thing to my backlog, but I'm not yet sure how / if I want to display the info.
