### ISSUE TITLE
Firestone dont working

### ISSUE THREAD

**Issue by bloodsinc** [Zero-to-Heroes/firestone#85]
The firestone dont wanna working at all in hearthstone , doing all the steps from here https://github.com/Zero-to-Heroes/firestone/wiki/FAQ---Troubleshooting , and nothing changes , starting overwolf-firestone , than HS and nothing happend

**Comment by sebastientromp** [comment]
Sorry I never got back to you on this. The best case when things don't work like that is to open a bug from within Firestone, which will send me all the logs.
