### ISSUE TITLE
Add filter by region

### ISSUE THREAD

**Issue by GCorbel** [Zero-to-Heroes/firestone#86]
I play on NA and Europe and my stats are mixed together which make no sense in the rank's graph. I think add a region filter will fix the issue.

![image](https://user-images.githubusercontent.com/1296201/169198105-c6d7732d-96c1-415c-ab78-cd1a0b932d3b.png)

**Comment by sebastientromp** [comment]
Thanks for the report!
The app indeed doesn't really have multi-region support. 
However I have started logging the region in which the games are played a while ago, so I should now be able to implement some basic filters in the more important screens.
Cheers :)

**Comment by sebastientromp** [comment]
This should be implemented now. Let me know if the issue needs to be reopened :)
